package com.sgmw.sales.app.sample.repository.mybatis;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.sgmw.sales.app.sample.domain.ActivitySignUp;
import com.sgmw.sales.app.sample.domain.ActivitySignUpExample;

public interface ActivitySignUpMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_sign_up_tbl
     *
     * @mbggenerated
     */
    int countByExample(ActivitySignUpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_sign_up_tbl
     *
     * @mbggenerated
     */
    int deleteByExample(ActivitySignUpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_sign_up_tbl
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_sign_up_tbl
     *
     * @mbggenerated
     */
    int insert(ActivitySignUp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_sign_up_tbl
     *
     * @mbggenerated
     */
    int insertSelective(ActivitySignUp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_sign_up_tbl
     *
     * @mbggenerated
     */
    List<ActivitySignUp> selectByExampleWithBLOBs(ActivitySignUpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_sign_up_tbl
     *
     * @mbggenerated
     */
    List<ActivitySignUp> selectByExample(ActivitySignUpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_sign_up_tbl
     *
     * @mbggenerated
     */
    ActivitySignUp selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_sign_up_tbl
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ActivitySignUp record, @Param("example") ActivitySignUpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_sign_up_tbl
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") ActivitySignUp record, @Param("example") ActivitySignUpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_sign_up_tbl
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ActivitySignUp record, @Param("example") ActivitySignUpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_sign_up_tbl
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ActivitySignUp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_sign_up_tbl
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(ActivitySignUp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_sign_up_tbl
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ActivitySignUp record);
    
    boolean createNewTable();
    
    String getTableName();
}