package com.sgmw.sales.app.sample.domain;

import java.io.Serializable;
import java.util.Date;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(value="报名对象")
public class ActivitySignUp implements Serializable{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_sign_up_tbl.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_sign_up_tbl.type
     *
     * @mbggenerated
     */
	@ApiModelProperty(value="报名类型")
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_sign_up_tbl.user_id
     *
     * @mbggenerated
     */
	@ApiModelProperty(value="用户ID")
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_sign_up_tbl.sign_up_date
     *
     * @mbggenerated
     */
	@ApiModelProperty(value="报名日期")
    private Date signUpDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_sign_up_tbl.additonal
     *
     * @mbggenerated
     */
	@ApiModelProperty(value="附加信息")
    private String additonal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_sign_up_tbl.message
     *
     * @mbggenerated
     */
	@ApiModelProperty(value="留言信息")
    private String message;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_sign_up_tbl.id
     *
     * @return the value of activity_sign_up_tbl.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_sign_up_tbl.id
     *
     * @param id the value for activity_sign_up_tbl.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_sign_up_tbl.type
     *
     * @return the value of activity_sign_up_tbl.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_sign_up_tbl.type
     *
     * @param type the value for activity_sign_up_tbl.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_sign_up_tbl.user_id
     *
     * @return the value of activity_sign_up_tbl.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_sign_up_tbl.user_id
     *
     * @param userId the value for activity_sign_up_tbl.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_sign_up_tbl.sign_up_date
     *
     * @return the value of activity_sign_up_tbl.sign_up_date
     *
     * @mbggenerated
     */
    public Date getSignUpDate() {
        return signUpDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_sign_up_tbl.sign_up_date
     *
     * @param signUpDate the value for activity_sign_up_tbl.sign_up_date
     *
     * @mbggenerated
     */
    public void setSignUpDate(Date signUpDate) {
        this.signUpDate = signUpDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_sign_up_tbl.additonal
     *
     * @return the value of activity_sign_up_tbl.additonal
     *
     * @mbggenerated
     */
    public String getAdditonal() {
        return additonal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_sign_up_tbl.additonal
     *
     * @param additonal the value for activity_sign_up_tbl.additonal
     *
     * @mbggenerated
     */
    public void setAdditonal(String additonal) {
        this.additonal = additonal == null ? null : additonal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_sign_up_tbl.message
     *
     * @return the value of activity_sign_up_tbl.message
     *
     * @mbggenerated
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_sign_up_tbl.message
     *
     * @param message the value for activity_sign_up_tbl.message
     *
     * @mbggenerated
     */
    public void setMessage(String message) {
        this.message = message == null ? null : message.trim();
    }
}